### ISSUE TITLE
[WIP] Tracking Bengali Documentation Progress of Glossary

### ISSUE THREAD

**Issue by mitul3737** [BRACU-Tech-Enthusiasts/CNCF-Kubernetes-Documentation#2]
This issue tracks Bengali Documentation progress.

# Join the Slack

- Join the [Kubernetes Slack](https://slack.k8s.io/)
- Join the [kubernetes-docs-bn](https://kubernetes.slack.com/messages/kubernetes-docs-bn), [ sig-docs-localizations](https://kubernetes.slack.com/messages/sig-docs-localizations) 

# Checklist to translate a term
1.	Check that no one else has claimed the page in the comments below.
2.	Comment below the page that you would like to localize, focus on one page per PR, at a time.
2.	Comment below the page that you would like to localize, focus on one page per PR, at a time.
3.	Maintainers will add your username and Pull Request next to your selected page in the below checklist.
4.	Fork this repo, make your localizations, and submit a pull request following the name convention ``[bn]  Documentation <file_name.md>``.
ex: [bn] Documentation  cloud_native_apps.md
5.	tag/ping a maintainer to make it easier to track progress

# Points to remember:

- Please use the word ``documentation`` instead of translation.

- For more information on how to contribute, check out [guidelines](https://kubernetes.io/docs/contribute/)

# For Volunteers
Volunteers can comment below on this issue with the page-name they are interested in documentation
Please also provide a placeholder PR in your comment.
Example: ``I would like to contribute to content/bn/<xyz.md>``

# Priorities
We need at least 52 pages documented in Bengali  before go-live, below are some suggested terms to work:

- [ ] README-bn.md
     content/bn/releases/_index.md
     config.toml
     content/bn/docs/home/_index.md
     content/bn/docs/setup/_index.md
     content/bn/docs/tutorials/kubernetes-basics/_index.html
    @mitul3737 
    https://github.com/kubernetes/website/pull/31644

- [ ] content/bn /_index.html

- [ ] content/bn /case-studies/_index.html
  @Imtiaz1234
  https://github.com/kubernetes/website/pull/31676

- [ ] content/bn/docs/concepts/overview/what-is-kubernetes.md

- [ ] content/bn/docs/contribute/_index.md

- [ ] content/bn/docs/home/supported-doc-versions.md

- [ ] content/bn/docs/reference/_index.md

- [ ] content/bn/docs/reference/glossary/index.md

- [ ] content/bn/docs/setup/best-practices/_index.md

- [ ] content/bn/docs/setup/learning-environment/_index.md

- [ ] content/bn/docs/setup/production-environment/_index.md

- [ ] content/bn/docs/setup/production-environment/turnkey-solutions.md

- [ ] content/bn/docs/setup/production-environment/windows/_index.md

- [ ] content/bn/docs/tasks/_index.md

- [ ] content/bn/docs/tasks/tools/_index.md

- [ ] content/bn/docs/tasks/tools/included/_index.md

- [ ] content/bn/docs/tasks/tools/included/kubectl-convert-overview.md

- [ ] content/bn/docs/tasks/tools/included/kubectl-whats-next.md

- [ ] content/bn/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md

- [ ] content/bn/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md

- [ ] content/bn/docs/tasks/tools/included/optional-kubectl-configs-zsh.md

- [ ] content/bn/docs/tasks/tools/included/verify-kubectl.md

- [ ] content/bn/docs/tasks/tools/install-kubectl-linux.md

- [ ] content/bn/docs/tasks/tools/install-kubectl-macos.md

- [ ] content/bn/docs/tasks/tools/install-kubectl-windows.md

- [ ] content/bn/docs/tutorials/_index.md

- [ ] content/bn/docs/tutorials/kubernetes-basics/create-cluster/_index.md

- [ ] content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html

- [ ] content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html

- [ ] content/bn/docs/tutorials/kubernetes-basics/deploy-app/_index.md

- [ ] content/bn/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html

- [ ] content/bn/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html

- [ ] content/bn/docs/tutorials/kubernetes-basics/explore/_index.md

- [ ] content/bn/docs/tutorials/kubernetes-basics/explore/explore-interactive.html

- [ ] content/bn/docs/tutorials/kubernetes-basics/explore/explore-intro.html
- [ ] content/bn/docs/tutorials/kubernetes-basics/expose/_index.md
- [ ] content/bn/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
- [ ] content/bn/docs/tutorials/kubernetes-basics/expose/expose-intro.html

- [ ] content/bn/docs/tutorials/kubernetes-basics/scale/_index.md

- [ ] content/bn/docs/tutorials/kubernetes-basics/scale/scale-interactive.html

- [ ] content/bn/docs/tutorials/kubernetes-basics/scale/scale-intro.html

- [ ] content/bn/docs/tutorials/kubernetes-basics/update/_index.md

- [ ] content/bn/docs/tutorials/kubernetes-basics/update/update-interactive.html

- [ ] content/bn/docs/tutorials/kubernetes-basics/update/update-intro.html

- [ ] content/bn/includes/task-tutorial-prereqs.md

- [ ] data/i18n/bn/bn.toml

- [ ] static/_redirects

**Comment by mitul3737** [comment]
I am working on `` README-bn.md``, ``config.toml``, ``content/bn/docs/home/_index.md``, ``content/bn/docs/setup/_index.md``, ``content/bn/docs/tutorials/kubernetes-basics/_index.html``, ``content/bn/releases/_index.md``

**Comment by Imtiaz1234** [comment]
Can I please work on ``content/bn /case-studies/_index.html`` ?

**Comment by mitul3737** [comment]
You can work on this @Imtiaz1234

**Comment by Imtiaz1234** [comment]
Created a PR https://github.com/kubernetes/website/pull/31676 for ``content/bn /case-studies/_index.html``

**Comment by nazma1234** [comment]
Can I please contribute to ``content/hi/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html`` ?
